### ISSUE TITLE
Any code?

### ISSUE THREAD

**Issue by rrooggiieerr** [Floris497/bluetooth-scale#1]
Hi!

Did you create any code to work with this scale? I'd like to know how it works so I can create an integration for Home Assistant

**Comment by Floris497** [comment]
Oh yes absolutely, I'm not near my computer now (or anyway the one where this code is) but I'll give you something. Feel free to remind me if I forget 😅 (only got the weight to work, the body fat calculations were not important for me) 
I don't understand why I didn't upload the code.. I thought it was there all the time

**Comment by rrooggiieerr** [comment]
That's great, I'm looking forward to it

**Comment by freijn** [comment]
looking forward as well !! :-)

**Comment by rrooggiieerr** [comment]
@Floris497 just a friendly reminder if you could share your code

**Comment by Floris497** [comment]
https://github.com/Floris497/WNoter apparently it was here...

**Comment by freijn** [comment]
And I can tell you the basics is working now!   Many thanks Rogier!

**Comment by rrooggiieerr** [comment]
@Floris497 thanks, I'll use your code to validate what I figured out in the meantime
